### ISSUE TITLE
Support for ibmiotf 0.1.3 release

### ISSUE THREAD

**Issue by durera** [ibm-messaging/iotf-phonemotion#2]
0.1.3 brings the ability to pass in the log handlers that will be used by the client library ... this sample should be updated to pass in a single nullHandler to properly disable the logging in the server proxies application instances.

see: https://github.com/ibm-messaging/iot-python/commit/75ab0334477089aa318f9b2971d5bd1c79fffdd7

**Comment by slaupster** [comment]
moved to 0.1.4 in https://github.com/ibm-messaging/iotf-phonemotion/commit/61c4149deada4a03a3ff5937526f6e0ba8cf9e6b
